### ISSUE TITLE
vec4s member mismatch in leif.c file during build

### ISSUE THREAD

**Issue by eshwar4202** [cococry/lyssa#5]
make rebuild install
make clean
make[1]: Entering directory '/home/eshwar/lyssa'
rm -rf ./bin
rm -rf ./vendor/leif/lib
make[1]: Leaving directory '/home/eshwar/lyssa'
make leif
make[1]: Entering directory '/home/eshwar/lyssa'
make -C ./vendor/leif/
make[2]: Entering directory '/home/eshwar/lyssa/vendor/leif'
mkdir lib
gcc `pkg-config --cflags glfw3 cglm libclipboard` -Ivendor/glad/include -Ivendor/stb_image/ -Ivendor/stb_truetype -Ivendor/stb_image_resize -DLF_GLFW -O3 -ffast-math  -c leif.c -o lib/leif.o
leif.c: In function ‘lf_text_render’:
leif.c:3006:44: error: ‘vec4s’ has no member named ‘r’
 3006 |           const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                            ^
leif.c:3006:57: error: ‘vec4s’ has no member named ‘g’
 3006 |           const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                         ^
leif.c:3006:70: error: ‘vec4s’ has no member named ‘b’
 3006 |           const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                      ^
leif.c:3006:83: error: ‘vec4s’ has no member named ‘a’
 3006 |           const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                                   ^
leif.c: In function ‘lf_text_render_wchar’:
leif.c:3139:42: error: ‘vec4s’ has no member named ‘r’
 3139 |         const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                          ^
leif.c:3139:55: error: ‘vec4s’ has no member named ‘g’
 3139 |         const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                       ^
leif.c:3139:68: error: ‘vec4s’ has no member named ‘b’
 3139 |         const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                    ^
leif.c:3139:81: error: ‘vec4s’ has no member named ‘a’
 3139 |         const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                                 ^
leif.c: In function ‘lf_rect_render’:
leif.c:3215:52: error: ‘vec4s’ has no member named ‘r’
 3215 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                    ^
leif.c:3215:72: error: ‘vec4s’ has no member named ‘g’
 3215 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                        ^
leif.c:3215:92: error: ‘vec4s’ has no member named ‘b’
 3215 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                                            ^
leif.c:3215:112: error: ‘vec4s’ has no member named ‘a’
 3215 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                                                                ^
leif.c:3221:38: error: ‘vec4s’ has no member named ‘r’
 3221 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                      ^
leif.c:3221:51: error: ‘vec4s’ has no member named ‘g’
 3221 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                   ^
leif.c:3221:64: error: ‘vec4s’ has no member named ‘b’
 3221 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                ^
leif.c:3221:77: error: ‘vec4s’ has no member named ‘a’
 3221 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                             ^
leif.c: In function ‘lf_image_render’:
leif.c:3307:52: error: ‘vec4s’ has no member named ‘r’
 3307 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                    ^
leif.c:3307:72: error: ‘vec4s’ has no member named ‘g’
 3307 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                        ^
leif.c:3307:92: error: ‘vec4s’ has no member named ‘b’
 3307 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                                            ^
leif.c:3307:112: error: ‘vec4s’ has no member named ‘a’
 3307 |     const vec4 border_color_arr = {border_color_zto.r, border_color_zto.g, border_color_zto.b, border_color_zto.a};
      |                                                                                                                ^
leif.c:3313:38: error: ‘vec4s’ has no member named ‘r’
 3313 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                      ^
leif.c:3313:51: error: ‘vec4s’ has no member named ‘g’
 3313 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                   ^
leif.c:3313:64: error: ‘vec4s’ has no member named ‘b’
 3313 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                ^
leif.c:3313:77: error: ‘vec4s’ has no member named ‘a’
 3313 |     const vec4 color_arr = {color_zto.r, color_zto.g, color_zto.b, color_zto.a};
      |                                                                             ^
leif.c: In function ‘lf_color_from_zto’:
leif.c:3497:33: error: ‘vec4s’ has no member named ‘r’
 3497 |   return (LfColor){(uint8_t)(zto.r * 255.0f), (uint8_t)(zto.g * 255.0f), (uint8_t)(zto.b * 255.0f), (uint8_t)(zto.a * 255.0f)};
      |                                 ^
leif.c:3497:60: error: ‘vec4s’ has no member named ‘g’
 3497 |   return (LfColor){(uint8_t)(zto.r * 255.0f), (uint8_t)(zto.g * 255.0f), (uint8_t)(zto.b * 255.0f), (uint8_t)(zto.a * 255.0f)};
      |                                                            ^
leif.c:3497:87: error: ‘vec4s’ has no member named ‘b’
 3497 |   return (LfColor){(uint8_t)(zto.r * 255.0f), (uint8_t)(zto.g * 255.0f), (uint8_t)(zto.b * 255.0f), (uint8_t)(zto.a * 255.0f)};
      |                                                                                       ^
leif.c:3497:114: error: ‘vec4s’ has no member named ‘a’
 3497 |   return (LfColor){(uint8_t)(zto.r * 255.0f), (uint8_t)(zto.g * 255.0f), (uint8_t)(zto.b * 255.0f), (uint8_t)(zto.a * 255.0f)};
      |                                                                                                                  ^
leif.c: In function ‘load_font’:
leif.c:1028:3: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1028 |   fread(buffer, 1, fileSize, file);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
leif.c:1040:3: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1040 |   fread(buf, 1, 1<<20, fopen(filepath, "rb"));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:9: lib/leif.o] Error 1
make[2]: Leaving directory '/home/eshwar/lyssa/vendor/leif'
make[1]: *** [Makefile:22: leif] Error 2
make[1]: Leaving directory '/home/eshwar/lyssa'
make: *** [Makefile:40: rebuild] Error 2

**Comment by cococry** [comment]
Do you have cglm installed and in your systems include/library paths?

**Comment by eshwar4202** [comment]
what is that

**Comment by eshwar4202** [comment]
> Do you have cglm installed and in your systems include/library paths?

thx i installed it and that error is fixed

new error:

/usr/bin/ld: /usr/local/lib/libclipboard.a(clipboard_x11.c.o): undefined reference to symbol 'xcb_get_setup'
/usr/bin/ld: /lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:26: build] Error 1
make[1]: Leaving directory '/home/eshwar/lyssa'
make: *** [Makefile:41: rebuild] Error 2

**Comment by eshwar4202** [comment]
> > Do you have cglm installed and in your systems include/library paths?
> 
> thx i installed it and that error is fixed
> 
> new error:
> 
> /usr/bin/ld: /usr/local/lib/libclipboard.a(clipboard_x11.c.o): undefined reference to symbol 'xcb_get_setup' /usr/bin/ld: /lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status make[1]: *** [Makefile:26: build] Error 1 make[1]: Leaving directory '/home/eshwar/lyssa' make: *** [Makefile:41: rebuild] Error 2

never mind i added -lxcb tag in the makefile dependencies list now it ran and working shall i close this. or pls say if there was any other way to resolve the above error.

**Comment by eshwar4202** [comment]
new error while lyssa is running

is this due to song name

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
[1]    32530 IOT instruction (core dumped)  lyssa

**Comment by cococry** [comment]
yeah that is probably caused by a name with some specific unicode symbols in it. 

does renaming the file work? the files of downloaded playlists go into .lyssa/downloaded_playlists so change the name there if you are talking about a downloaded playlist

**Comment by cococry** [comment]
> > > Do you have cglm installed and in your systems include/library paths?
> 
> > 
> 
> > thx i installed it and that error is fixed
> 
> > 
> 
> > new error:
> 
> > 
> 
> > /usr/bin/ld: /usr/local/lib/libclipboard.a(clipboard_x11.c.o): undefined reference to symbol 'xcb_get_setup' /usr/bin/ld: /lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status make[1]: *** [Makefile:26: build] Error 1 make[1]: Leaving directory '/home/eshwar/lyssa' make: *** [Makefile:41: rebuild] Error 2
> 
> 
> 
> never mind i added -lxcb tag in the makefile dependencies list now it ran and working shall i close this. or pls say if there was any other way to resolve the above error.

you did the right thing. i also added xcb link to the makefile in the repo.

**Comment by eshwar4202** [comment]
> yeah that is probably caused by a name with some specific unicode symbols in it.
> 
> does renaming the file work? the files of downloaded playlists go into .lyssa/downloaded_playlists so change the name there if you are talking about a downloaded playlist

it worked. after i removed a lot of symbols thx ill close this bye
