### ISSUE TITLE
Failed to open font file

### ISSUE THREAD

**Issue by SwishersSweets** [cococry/lyssa#6]
When I try to launch Lyssa after building it, it  gives me the following error:
"[LEIF ERROR]: Failed to open font file '/home/[my name]/.leif/assets/fonts/inter.ttf'

Segmentation fault (core dumped)"

I'm on Arch and used yay instead of paru to install the build dependencies for lyssa and leif if that can help.

**Comment by cococry** [comment]
does the file exist? 

do you have a .leif folder in your hole directory?

**Comment by iliesh** [comment]
Duplicated:
https://github.com/cococry/lyssa/issues/1#issuecomment-2018426906

**Comment by SwishersSweets** [comment]
> does the file exist?

Yes.

> do you have a .leif folder in your home directory?

I do have a .leif folder in my home directory.

I will close this issue I guess because iliesh has the same problem as me.
